### ISSUE TITLE
Database integration with UI

### ISSUE THREAD

**Issue by GanzB02** [afislonge/deepfake-detection-project#29]

**Comment by afislonge** [comment]
@14th March
Yesterday, I setup the development env.
Today, no coding on the project due to blocker
Blocker, Mongo db yet to be setup

**Comment by afislonge** [comment]
@17h March
I did not work on the project yesterday.
I pull updated codebase to have access to the mongo db code. I will start db integration next week
I have no blocker

**Comment by afislonge** [comment]
## 20th March

Integrated Mongo db for reporting. Optimize the code for model integration and reporting.
Blocker : None
Next week : I will style the UI
